version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=123456
    ports:
      - "3307:3306" #<local-port>:<container-port>
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/coviddatabase.sql
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: covid-spring-boot-app
    restart: always
    ports:
      - "8181:8080" #<local-port>:<container-port>
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/covid?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    stdin_open: true
    tty: true

volumes:
  db: